name: Deploy code changes to fastapi-app

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_and_push_docker_image:
    name: build and push docker image to docker hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS}}

      - name: extract docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chykee67/fastapi-app

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: chykee67/fastapi-app:latest
          labels: ${{steps.meta.outputs.labels}}

  deploy:
    name: deploy changes to fastapi-app
    runs-on: ubuntu-latest
    needs: [build_and_push_docker_image]
    steps:
      - name: run docker-compose on app server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            sudo docker compose down
            sudo docker rmi -f $(sudo docker images -q)
            sudo docker compose pull
            sudo docker compose up -d