name: Test Fastapi-app

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [feature/Amazingfeature]

jobs:
  test:
    name: test fastapi-app using pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: test with pytest
        run: pytest